### PR TITLE
Increase visibility and discoverability of API changelog

### PR DESCRIPTION
**Pull request by dylanegan**

### CODE REVIEW

**Comment by dylanegan** [comment]
@laurapacilio I've noticed in the revamp of documentation that a pull request template with a check for making sure folks update the API changelog has disappeared. I'm concerned this might have a knock on effect in that API updates might have been missed in the changelog.

Before making a new template, I'd love to know how best we can ensure API changes include an API changelog update.

**Comment by laurapacilio** [comment]
Hey @dylanegan - great point! I'll get the PR template from terraform-website copied over. But I do not remember there ever being a part of that template: https://github.com/hashicorp/terraform-website/blob/master/.github/pull_request_template.md

Is there another template the references the API changelog that you're referring to? If not, would you like me to add an item to the PR checklist that references the changelog/API docs?

**Comment by dylanegan** [comment]
@laurapacilio should I update the template in this PR too?

**Comment by laurapacilio** [comment]
Hello! No need! I've merged a PR that I believe will solve this issue for PRs to this repository going forward! :)

**Comment by laurapacilio** [comment]
It's okay :) We can always open another PR!

**Pull request merged**
