### PR TITLE
Add query option to agent pool list API

### PR DESCRIPTION
**Pull request by JarrettSpiker**
### What
Add query parameter to agent pool list API docs

We will wait on merging this until the feature has been turned on

Related:
 - [Asana](https://app.asana.com/0/1201654039499505/1202293086474692/f)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202293596899906

### CODE REVIEW

**Review by laurapacilio — APPROVED** [review]
Approving since this seems right. 🚀 

Quick question --> we don't need to show it in the sample request or response, right? I don't think we typically do this with the optional parameters, but wanted to mention just in case.

**Comment by JarrettSpiker** [comment]
> Quick question --> we don't need to show it in the sample request or response, right? I don't think we typically do this with the optional parameters, but wanted to mention just in case.

Oh, we did actually add some metadata to the responses around this search parameter...it probably isn't the most interesting to most users, but I will quickly add it just in case. Thanks for the reminder!

**Review by bethanyr — CHANGES_REQUESTED** [review]
@laurapacilio & @JarrettSpiker  - can you also update the [api changelog](https://www.terraform.io/cloud-docs/api-docs/changelog) with this change?

**Comment by JarrettSpiker** [comment]
> @laurapacilio & @JarrettSpiker - can you also update the [api changelog](https://www.terraform.io/cloud-docs/api-docs/changelog) with this change?

@laurapacilio @bethanyr sure! Question though, do we need to mention in the changelog when the API will be available in TFE (since it is available in TFC now, but wont be available in TFE until the next release)? Or does the versioned docs change take care of that?

**Comment by bethanyr** [comment]
I don't think folks have been consistent about updating when an api change is available in TFE. I think if the API change will be available in the next TFE release then it isn't being called out, but maybe @laurapacilio has some guidance.

**Comment by JarrettSpiker** [comment]
@bethanyr oops, I saw the green merge button and didn't notice that your requested changes were still marked as outstanding, my mistake!

I added the change to the changelog as requested, please let me know if you see any issues and I can open a new change!

**Pull request merged**
